### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by 20avva** [changhuixu/canvas-animation-demos#1]
I understand this project may no longer be maintained, but I feel that it is in the interest of devs learning to use HTML Canvas and TS together to have more comments in the script files. I hope I don't come off as rude. I've just found this repo and I'm looking forward to puzzling it out myself and then hopefully writing some comments and making PR's.

**Comment by changhuixu** [comment]
@20avva  Good thoughts. Comments are useful for beginners.
Please feel free to make PRs. Or add Wiki pages.
Thank you.
